# The channel key should match the nightly rust-toolchain.toml in the embassy repo
[toolchain]
channel = "1.92"
components = [ "rust-src", "rustfmt", "llvm-tools", "clippy" ]
targets = [ "thumbv7em-none-eabi" ]
